config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'static_pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-header">
    <%= link_to "Alexis Trinh", root_url, {class: "navbar-brand", id: "logo"} %>
  </div>
  <div class="container-fluid">
    <ul class='nav navbar-nav navbar-right'>
    <li><%= link_to 'About', static_pages_home_path %></li>
    <li><%= link_to 'Portfolio', static_pages_home_path %></li>
  </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<div class="social row">
  <div class="github col-sm-2">
    <img height="50" width="50" src="http://www.cs.columbia.edu/~stratos/images/github.png">
    <a href="#">Github</a>
  </div>
</div>

<div id="projects">
  <ul>
      <li><img height="50" width="50" src="http://www.cs.columbia.edu/~stratos/images/github.png"></li>
      <li><img height="50" width="50" src="http://www.cs.columbia.edu/~stratos/images/github.png"></li>
      <li><img height="50" width="50" src="http://www.cs.columbia.edu/~stratos/images/github.png"></li>
  </ul>
</div>